import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

// 1) Load local .env for provider keys, QuickNode creds, etc.
dotenv.config();

// 2) Merge in Anvil RPC overrides generated by start:anvil
//    This will not override already-set variables.
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const anvilEnvPath = path.resolve(__dirname, '../../onchain-actions/.env.tmp.test');
dotenv.config({ path: anvilEnvPath });
